[package]
name = "pqbip39"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "2.0.12", default-features = false }

[features]
default = ["none_pq", "pq"]
pq = []
none_pq = []
